### ISSUE TITLE
New example configurations do not work

### ISSUE THREAD

**Issue by subhasutra** [taj-ny/kwin-gestures#29]
After updating I tried the new example gestures, but it does not work and using ` journalctl --boot=0 -g "kwin_gestures:" -n 5 ` gives this error.
```
kwin_wayland[888]: kwin_gestures: Failed to load configuration: No gestures specified (line -1, column -1)
```
The new .yml config file is being generated normally however. Is there something I'm doing incorrectly?

**Comment by taj-ny** [comment]
There's an example at the end of [configuration.md](https://github.com/taj-ny/kwin-gestures/blob/main/docs/configuration.md), example gestures don't include the device.
```yaml
touchpad:
  speed:
    swipe_threshold: 15

  gestures:
    # put gestures here
    - type: pinch
      fingers: 2
      direction: in

      actions:
        - plasma_shortcut: kwin,Window Close
```
