### ISSUE TITLE
Mouse input action

### ISSUE THREAD

**Issue by taj-ny** [taj-ny/kwin-gestures#31]
The *keyboard* action will be renamed to *input* and it will also gain the ability to send mouse input.

This would make it possible to make a three finger drag gesture (although if I'm not wrong, the acceleration for gestures is different).
```yaml
actions:
  - on: begin
    input:
      - keyboard: [ +leftmeta ]
      - mouse: [ +left ]
    # - keyboard: [ a ] - One device can be used multiple times in the input action
  
  - on: update
    input:
      - mouse: [ move_by_delta 0.25 ] # 0.25 - delta multiplier

  - on: end
    input:
      - keyboard: [ -leftmeta ]
      - mouse: [ -left ] 
```

Requires #30.
