### ISSUE TITLE
Issue with config file

### ISSUE THREAD

**Issue by dymdipii** [taj-ny/kwin-gestures#33]
I'm seeing the following error in my journal logs

```bash
kwin_gestures: Failed to load configuration: No gestures specified (line -1, column -1)
```

This is my config file:
```yaml
touchpad:
  gestures:
    # Window switching
    - type: swipe
      direction: left_right
      fingers: 4
      speed: fast
      actions:
      - on: begin
        keyboard: +leftalt tab

      - on: update
        interval: -75
        keyboard: leftshift+tab

      - on: update
        interval: 75
        keyboard: tab

      - on: end_cancel
        keyboard: -leftalt

    # Quick window switching (left)
    - type: swipe
      direction: left
      fingers: 4
      speed: slow
      actions:
      - on: begin
        keyboard: leftalt+leftshift+tab

    # Quick window switching (right)
    - type: swipe
      direction: right
      fingers: 4
      speed: slow
      actions:
      - on: begin
        keyboard: leftalt+tab

```

I've checked this in a yaml validator and it all seems fine.

I get the same error even if I use the example config:

```yaml
touchpad:
  speed:
    swipe_threshold: 15

  gestures:
    - type: pinch
      fingers: 2
      direction: in

      actions:
        - plasma_shortcut: kwin,Window Close
```
