### ISSUE TITLE
Failed to load configuration: Invalid keyboard key ('-')

### ISSUE THREAD

**Issue by wangbin19860909** [taj-ny/kwin-gestures#62]
I want to apply pinch gestures to zoom in/out, but configuration load failed, I also tried plasma_shortcut: Zoom In/ Zoom Out, does not work either.
How to config "ctrl + =" and "ctrl + -"?

```yml
- type: p
  fingers: 2
  direction: in

  actions:
    - on: update
      input:
        - keyboard: [leftctrl+-]
```
