### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Oneechan69** [taj-ny/kwin-gestures#65]
I'm trying to make swiping right with three fingers do `CTRL Tab` but I can't get it working. This is my `~/.config/kwingestures.yml`, excuse me if I overlooked anything or if I made noob errors.

```yaml
touchpad:
  speed:
    swipe_threshold: 15

  gestures:
  - type: swipe
    fingers: 3
    direction: right

    actions:
      input:
        keyboard: [ leftctrl+tab ]
```

When I do `journalctl --boot=0 -g "kwin_gestures:" -n 5`, I get the error ` kwin_gestures: Failed to load configuration: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa (>
~ line -1, column -1)`, idk what to do with that.

**Comment by taj-ny** [comment]
Wrong indentation, also *actions* and *input* are lists.

```yaml
touchpad:
  speed:
    swipe_threshold: 15

  gestures:
    - type: swipe
      fingers: 3
      direction: right

      actions:
        - input:
          - keyboard: [ leftctrl+tab ]
```
