### ISSUE TITLE
keyboard_modifiers don't work?

### ISSUE THREAD

**Issue by dgudim** [taj-ny/kwin-gestures#82]
Maybe I am doing something wrong, but I can't get `keyboard_modifiers` to work, the gesture is still triggered regardless

```
    - type: hold
      fingers: 3
      threshold: 750
      keyboard_modifiers: [alt]

      actions:
        - on: begin
          plasma_shortcut: kwin,Window Close
```
