### ISSUE TITLE
Suggestion: gesture direction sensitivity

### ISSUE THREAD

**Issue by Glampi42** [taj-ny/kwin-gestures#91]
It would be nice to be able to configure how the direction of the gesture, specifically swipes, is determined. For example, if there was a variable "vertical bias" with the default value 0.5. If it is set to 1, then any gesture is considered a vertical (up/down) gesture, and vice versa. Then one could configure gestures that have to be performed strictly horizontally, or can have a freedom range.

Usage example:
```
touchpad:
    gestures:
        # go back
        - type: swipe
          fingers: 2
          direction: left

          vertical_bias: 0.8

          actions:
            - on: end
              input:
                - keyboard: [ leftalt+left ]

        # go forward
        - type: swipe
          fingers: 2
          direction: right

          vertical_bias: 0.8

          actions:
            - on: end
              input:
                - keyboard: [ leftalt+right ]

```

With this config, most gestures will be considered vertical and will result in scrolling up/down; if the user makes a gesture strictly left/right, he will go back/go forward.
